# -*- coding: utf-8 -*-
"""
social_cards.py - Shareable cards (4:5 daily reading + 1:1 opinion cards)
========================================================================
Reads dashboard_data.json (generated by export_dashboard.py) and renders
light research-style PNG cards for social distribution:
  assets/daily_reading_<date>.png   daily reading card (4:5, 1080x1350)
  assets/card_benefit.png           1:1 - who benefits
  assets/card_loss.png              1:1 - who pays (and policy buffer)
  assets/card_sequence.png          1:1 - freeze then revaluation
  social/titles.md                  headline library (CN/EN)

Usage: python social_cards.py
"""
import os
import json
import datetime as dt
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import font_manager

BASE = os.path.dirname(os.path.abspath(__file__))
DATA = json.load(open(os.path.join(BASE, "dashboard_data.json"), encoding="utf-8"))
OUT = os.path.join(BASE, "assets")
SOC = os.path.join(BASE, "social")
os.makedirs(OUT, exist_ok=True)
os.makedirs(SOC, exist_ok=True)

# light research palette
INK = "#1f2937"; MUT = "#6b7280"; BLUE = "#2563eb"; GOLD = "#d97706"
GREEN = "#059669"; RED = "#dc2626"; LINE = "#e5e9f0"; PAPER = "#ffffff"

for name in ["SimHei", "Microsoft YaHei", "PingFang SC", "Noto Sans CJK SC"]:
    if name in {f.name for f in font_manager.fontManager.ttflist}:
        plt.rcParams["font.family"] = name
        break
plt.rcParams["axes.unicode_minus"] = False


def _img(w, h):
    fig = plt.figure(figsize=(w / 100.0, h / 100.0), facecolor=PAPER)
    ax = fig.add_axes([0, 0, 1, 1]); ax.axis("off")
    return fig, ax


def _txt(ax, x, y, s, size, color=INK, weight="normal", ha="left", va="top"):
    ax.text(x, y, s, fontsize=size, color=color, fontweight=weight,
            ha=ha, va=va, linespacing=1.55)


def _bar(ax, x, y0, v, w, c, maxabs):
    ax.add_patch(plt.Rectangle((x, y0 - 1.2), max(1, w * abs(v) / maxabs * 60),
                               2.4, facecolor=c, edgecolor="none"))
    ax.text(x + max(1, w * abs(v) / maxabs * 60) + 1, y0, "%+.1f%%" % v,
            fontsize=9.5, color=INK, va="center", fontweight="bold")


def daily_card():
    p = None
    for x in DATA["presets"]:
        if x["key"] == "p6":
            p = x
    live = DATA.get("live", {})
    spot = live.get("spot", 6.7108)
    vol = (live.get("vol3y") or 0.0284) * 100
    inert = (live.get("inertia_apprec") or 0.027) * 100
    out = DATA.get("outlook", {})
    y1 = (out.get("rows") or [{}])[0]
    m = p["macro"]
    today = dt.date.today().strftime("%Y-%m-%d")
    fig, ax = _img(1080, 1350)
    ax.add_patch(plt.Rectangle((0, 0), 1080, 12, facecolor=GOLD, edgecolor="none"))
    _txt(ax, 60, 1240, "RMB-Macro-Sim . 每日读数", 21, MUT, "bold")
    _txt(ax, 60, 1190, today, 15, MUT)
    _txt(ax, 60, 1090, "USD/CNY", 26, MUT, "bold")
    _txt(ax, 60, 1005, "%.4f" % spot, 96, BLUE, "bold")
    _txt(ax, 60, 935, "3y 波动率 %.2f%%   惯性升值 %.1f%%/年" % (vol, inert),
         18, MUT)
    ax.add_patch(plt.Rectangle((60, 700), 960, 1.6, facecolor=LINE, edgecolor="none"))
    _txt(ax, 60, 640, "年度展望 2026(最可能)", 20, INK, "bold")
    _txt(ax, 60, 590, "年末 USD/CNY %.3f  .  年变动 %+.2f%%  .  事件包络 %.3f ~ %.3f"
        % (y1.get("level", 0), y1.get("chg_pct", 0), y1.get("level_low", 0),
           y1.get("level_high", 0)), 19, INK)
    _txt(ax, 60, 550, "每 1 万美元 > %+.0f 元人民币" % y1.get("usd10k_cny", 0),
         19, GOLD, "bold")
    ax.add_patch(plt.Rectangle((60, 380), 960, 1.6, facecolor=LINE, edgecolor="none"))
    _txt(ax, 60, 320, "宏观风险(6%% 基准情景)", 20, INK, "bold")
    _txt(ax, 60, 270,
         "GDP 当量 %+.2f pt  |  就业暴露 %+.0f 万人  |  风险等级 %s  |  净效益 +2.68 万亿美元"
         % (m["gdp_cum_pt"], m["emp_exposed_wan"], m["risk_tier"]), 19, INK)
    _txt(ax, 60, 150, "升值不是代价,是重估的定价。但速冻先于重估-现金是弹药。",
         21, INK, "bold")
    _txt(ax, 60, 70, "github.com/Justinjchen-Cornell/RMB-Macro-Sim  .  研究框架,非投资建议",
         14, MUT)
    fp = os.path.join(OUT, "daily_reading_%s.png" % today)
    fig.savefig(fp, dpi=100)
    plt.close(fig)
    print("  [daily] %s" % fp)
    return fp


def _winner_rows():
    p = None
    for x in DATA["presets"]:
        if x["key"] == "p6":
            p = x
    order = ["semiconductor", "power_compute", "commodity_metals", "gold",
             "bank_insurance", "real_estate", "domestic_consumption"]
    cn = {"semiconductor": "半导体", "power_compute": "算力/电力",
          "commodity_metals": "工业金属", "gold": "黄金",
          "bank_insurance": "银行保险", "real_estate": "地产",
          "domestic_consumption": "消费"}
    out = []
    for k in order:
        if k in p["industry"] and p["industry"][k] > 0:
            out.append((cn[k], p["industry"][k]))
    return out[:5]


def _loser_rows():
    p = None
    for x in DATA["presets"]:
        if x["key"] == "p6":
            p = x
    out = [("低端制造", p["industry"]["export_lowend"]),
           ("高新出口", p["industry"]["export_hightech"]),
           ("新能源", p["industry"]["new_energy"])]
    return out


_FONT_PATH = None
def _fp():
    global _FONT_PATH
    if _FONT_PATH:
        return _FONT_PATH
    import os as _os
    for p in (r"C:\Windows\Fonts\msyh.ttc", r"C:\Windows\Fonts\simhei.ttf"):
        if _os.path.exists(p):
            _FONT_PATH = p
            return p
    raise RuntimeError("no CJK font")


def _pil_font(size, bold=True):
    from PIL import ImageFont
    try:
        return ImageFont.truetype(_fp(), size, index=0 if bold else 0)
    except Exception:
        return ImageFont.truetype(_fp(), size)


def _pil_card(path, accent, title, sub, rows, footer):
    """rows: list of (text, color_hex, size, bold, value_text or None)"""
    from PIL import Image, ImageDraw
    W, H = 1200, 1200
    img = Image.new("RGB", (W, H), "#ffffff")
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, W, 12], fill=accent)
    d.text((70, 56), title, font=_pil_font(38), fill=INK)
    d.text((70, 130), sub, font=_pil_font(20), fill=MUT)
    y = 250
    for item in rows:
        txt, col, size, bold, val = item
        if val:
            d.rectangle([70, y - 34, 76, y + 10], fill=col)
            d.text((110, y - 32), txt, font=_pil_font(size, bold), fill=INK)
            vtxt = val
            vb = d.textbbox((0, 0), vtxt, font=_pil_font(size, bold))
            d.text((W - 70 - (vb[2] - vb[0]), y - 32), vtxt,
                   font=_pil_font(size, bold), fill=col)
            y += 74
        else:
            d.text((110, y - 32), txt, font=_pil_font(size, bold), fill=col)
            y += int(size * 1.9)
    d.text((70, H - 120), footer, font=_pil_font(15), fill=MUT)
    img.save(path)
    print("  [pil] %s" % path)


def card_benefit():
    p = None
    for x in DATA["presets"]:
        if x["key"] == "p6":
            p = x
    cn = {"semiconductor": ("半导体", "#059669"), "power_compute": ("算力/电力", "#0891b2"),
          "commodity_metals": ("工业金属", "#059669"), "gold": ("黄金", "#d97706"),
          "bank_insurance": ("银行保险", "#2563eb")}
    rows = []
    order = ["semiconductor", "power_compute", "commodity_metals", "gold",
             "bank_insurance"]
    for k in order:
        if k in p["industry"] and p["industry"][k] > 0:
            rows.append((cn[k][0], cn[k][1], 24, True,
                         "%+.1f%%" % p["industry"][k]))
    rows.append(("背后: 全球美元流动性稀缺, 人民币资产成为最优容器", INK, 22, True, None))
    rows.append(("5 年净效益 +2.68 万亿美元, 约为出口损失的 9 倍", "#d97706", 26, True, None))
    _pil_card(os.path.join(OUT, "card_benefit.png"), "#059669",
              "人民币升值, 谁在受益?", "5 年累计利润冲击 - 6%% 基准情景(2000 次 MC)", rows,
              "github.com/Justinjchen-Cornell/RMB-Macro-Sim  -  研究框架,非投资建议")


def card_loss():
    p = None
    for x in DATA["presets"]:
        if x["key"] == "p6":
            p = x
    rows = [("低端制造", "#dc2626", 24, True, "%+.1f%%" % p["industry"]["export_lowend"]),
            ("高新出口", "#dc2626", 24, True, "%+.1f%%" % p["industry"]["export_hightech"]),
            ("新能源", "#dc2626", 24, True, "%+.1f%%" % p["industry"]["new_energy"])]
    rows.append(("代价是局部的, 收益是全局的", INK, 22, True, None))
    rows.append(("受损部门需要汇率避险工具 + 产业政策缓冲", MUT, 20, True, None))
    rows.append(("资本流入强度才是胜负手:", INK, 22, True, None))
    rows.append(("保守(历史常态)+1.99 万亿  ~  激进(美元荒)+3.91 万亿美元", "#d97706", 24, True, None))
    _pil_card(os.path.join(OUT, "card_loss.png"), "#dc2626",
              "人民币升值, 谁在付代价?", "5 年累计利润冲击 - 6%% 基准情景", rows,
              "github.com/Justinjchen-Cornell/RMB-Macro-Sim  -  研究框架,非投资建议")


def card_sequence():
    fig, ax = _img(1200, 1200)
    ax.add_patch(plt.Rectangle((0, 0), 1200, 12, facecolor=BLUE, edgecolor="none"))
    _txt(ax, 70, 1140, "顺序很重要: 速冻,然后才是重估", 34, INK, "bold")
    phases = [
        ("1 速冻期", "2026 Mid-Sep - Mid-Oct", "美元荒/VIX>35: 所有风险资产同跌, 现金 48% 是弹药", RED),
        ("2 错杀期", "Mid-Oct - Dec", "非理性抛售 = 买点; 分批三档: 黄金 -> 油/金属 -> 人民币资产", GOLD),
        ("3 重估期", "2027+", "升值兑现 + 资本涌入: A股/半导体/硬资产主升", GREEN)]
    y = 930
    for name, win, desc, col in phases:
        ax.add_patch(plt.Rectangle((70, y - 130), 1060, 110, facecolor="#f8fafc",
                                   edgecolor=LINE, linewidth=1.2))
        ax.add_patch(plt.Rectangle((70, y - 130), 8, 110, facecolor=col,
                                   edgecolor="none"))
        _txt(ax, 100, y - 60, name + "  .  " + win, 22, INK, "bold")
        _txt(ax, 100, y - 105, desc, 18, MUT)
        y -= 190
    _txt(ax, 70, 250, "反共识点: 升值不等于立刻涨 - 顺序做错,重估也救不了杠杆",
         20, INK, "bold")
    _txt(ax, 70, 90, "github.com/Justinjchen-Cornell/RMB-Macro-Sim  -  研究框架,非投资建议",
         15, MUT)
    fp = os.path.join(OUT, "card_sequence.png")
    fig.savefig(fp, dpi=100)
    plt.close(fig)
    print("  [card] %s" % fp)
    return fp


def titles_md():
    lines = [
        "# 观点标题库 (Social titles)\n",
        "## 中文",
        "- 升值不是代价,是重估的定价 - 人民币资产 5 年净效益 +2.68T$(=损失 9 倍)",
        "- 谁在为升值买单?低端制造 -28%;谁是赢家?半导体/硬资产 +8~15%",
        "- 先速冻,后重估: 现金是弹药,顺序比方向更重要",
        "- 即期已 6.71: 所谓 6% 情景不是假设,是正在发生的政策事实",
        "## English",
        "- Appreciation is not the cost - it is the repricing. Net benefit +2.68T$ (9x the loss).",
        "- Who pays for the strong yuan? Low-end mfg -28%. Who wins? Semi + hard assets.",
        "- Freeze first, revalue second: cash is ammo, sequencing beats direction.",
        "- Spot is already 6.71: the '6% scenario' is not hypothetical - it is policy fact.",
        "",
        "配图: assets/daily_reading_*.png (4:5) . card_benefit/loss/sequence.png (1:1)",
    ]
    with open(os.path.join(SOC, "titles.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("  [titles] social/titles.md")


if __name__ == "__main__":
    for fn in (daily_card, card_benefit, card_loss, card_sequence):
        try:
            fn()
        except Exception as e:
            print("FAILED", fn.__name__, type(e).__name__)
    titles_md()
